### PR TITLE
[feature] new resource: share

### PR DESCRIPTION
**Pull request by sjauld**
#34 

Tests all passing, although please not that shares require an ACCOUNTADMIN role.

I was going to wait until #33 was merged and then rebase but it looks like merge bot is on holidays? So I've tried to pre-emptively resolve merge conflicts, not sure how we'll go but I can always rebase again if there are issues.

### CODE REVIEW

**Comment by ryanking** [comment]
@sjauld mergebot might not work across forks, we haven't run into this situation before :)

I will merge that real quick and you can rebase.

**Comment by ryanking** [comment]
Actually did you mean https://github.com/Viostream/terraform-provider-snowflake/pull/1 ? Looks like it is in.

**Comment by sjauld** [comment]
No, I was referring to your #33 👍

**Comment by ryanking** [comment]
@sjauld I went ahead and merged manually. It was not being merged automatically because of failing travis-ci status checks, but the tests pass locally.

**Comment by sjauld** [comment]
Ok should be good to go now!

**Comment by ryanking** [comment]
@sjauld it seems the test if failing because the environment variables for auth are not present (at least I think so)

**Comment by ryanking** [comment]
I think you need to add those for your fork on travis-ci

**Comment by ryanking** [comment]
Are you able to get the acceptance tests working locally?

**Comment by sjauld** [comment]
Yes, these tests all passed locally. I'll look into adding the envs on Travis, however I'm still waiting for a clean test account from Snowflake, currently I'm just running the TestAccShare against our prod account and I don't want to do that for the whole test suite!

**Comment by sjauld** [comment]
I have added those ENVs to the travis configuration on my fork, but it seems to be having problems resolving the import path (github.com/chanzuckerberg/terraform-provider-snowflake vs github.com/viostream/terraform-provider-snowflake). I'll have to have more of a look into this tomorrow.

**Comment by ryanking** [comment]
@sjauld can you point me to a travis run with the import error?

**Comment by ryanking** [comment]
also, @sjauld, this change may fix the issue - https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/46

**Comment by sjauld** [comment]
Oh nice, I'll have a look when I get the chance. Tbh I had a few problems with Travis and due to time constraints I just forged on with local tests.

**Pull request merged**
