### PR TITLE
Add extra properties to users

### LINKED ISSUE #92: Feature Request:  add "email" as property to `snowflake_user` resource
Hi Team CZ

We've just adopted Snowflake, so I've just started using your cool TF provider.  Just a suggestion - can you add "email" as a property for the `snowflake_user` resource?

The reasoning is that, without associating an email with a new Snowflake user, it is impossible for that user to use the "Forgot Password" functionality.  Thanks!

### PR DESCRIPTION
**Pull request by sjauld**
Closes #92 

Note, I didn't add `middle_name`, since this is not returned by the SHOW USER DDL. We will need to make more significant changes and use DESCRIBE USER if we want support for `middle_name`.

### CODE REVIEW

**Comment by sjauld** [comment]
Ah damn, I only ran the acceptance test for the user resource, forgot about the related ones. Will fix and rerun.

**Comment by engauged** [comment]
This will be useful 👍

**Comment by ryanking** [comment]
I am still seeing acceptance test failures.

**Comment by sjauld** [comment]
Sorry, haven't had time to investigate. There is something strange going
on.

**Comment by ryanking** [comment]
@sjauld need any help with this?

**Comment by sjauld** [comment]
Sorry @ryanking , this has still not made it onto my todo list. Feel free to investigate if you have the time!

**Comment by sjauld** [comment]
Ok that's fixed - display name can be computed. Nice work on the refactor by the way!

**Pull request merged**
