### PR TITLE
feat: Add manage support cases account grants

### PR DESCRIPTION
**Pull request by gary-beautypie**
Add support cases management grants for accounts as per: https://docs.snowflake.com/en/user-guide/ui-support.html

## Test Plan

* [x] acceptance tests

## References

* https://docs.snowflake.com/en/user-guide/ui-support.html

### CODE REVIEW

**Comment by gary-beautypie** [comment]
hmm the failing test is unrelated but passes locally 🥲

**Comment by gary-beautypie** [comment]
hey, I'm running this against a clean test Snowflake account and everything passes just fine, not sure why there might be an extra procedure in the tests here when I'm not editing anything near that 😬  any common suggestions I could check as to why this might not pass here? sorry! and thanks!

**Comment by alldoami** [comment]
ah ya... this is a `procedures` resource issue... it would be nice to fix it...

**Comment by gary-beautypie** [comment]
Screenshot 2022-04-07 at 22 17 56
"SHOW PROCEDURES IN <x>" seems to now include this extra row in all accounts 🤔

**Review by alldoami — APPROVED** [review]

**Pull request merged**
