### PR TITLE
feat: table constraints

### PR DESCRIPTION
**Pull request by berosen**
* Adds null constraint to snowflake tables
* Adds specifying a primary key constraint to snowflake tables

## Test Plan

* [x] acceptance tests

## References

* #538
* https://docs.snowflake.com/en/sql-reference/constraints-overview.html

### CODE REVIEW

**Review by alldoami — APPROVED** [review]

**Comment by alldoami** [comment]
@berosen if you can update your branch, we'll be good to go!

**Comment by berosen** [comment]
> @berosen if you can update your branch, we'll be good to go!

Sure thing! Thank you!

**Pull request merged**
