### PR TITLE
feat: Add replication support

### PR DESCRIPTION
**Pull request by anton-chekanov**
Add support for allowing replication of a database and creating a database out of available replica.

## Test Plan

* [x] acceptance tests for database and replica
* [x] unit tests for database

## References
* https://docs.snowflake.com/en/user-guide/database-replication-config.html
* https://docs.snowflake.com/en/sql-reference/sql/alter-database.html#database-replication-and-failover-syntax
* https://docs.snowflake.com/en/sql-reference/sql/show-replication-databases.html
* Fixed version of https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/672

### CODE REVIEW

**Comment by alldoami** [comment]
run `make-docs`

**Comment by alldoami** [comment]
Could you address the test failures?

**Comment by yakui-lover** [comment]
I believe I have addressed them shortly before your comment, hence the tests being green right now.

**Comment by anton-chekanov** [comment]
I believe I have addressed them shortly before your comment, hence the tests being green right now.

**Comment by alldoami** [comment]
```
database_acceptance_test.go:56: Step 1/4 error: Check failed: Check 4/5 error: snowflake_database.db: Attribute 'replication_is_primary' expected "true", got "false"
```

**Comment by alldoami** [comment]
run `make docs`

**Review by alldoami — APPROVED** [review]

**Pull request merged**
