### PR TITLE
[docs] import and example for external table

### PR DESCRIPTION
**Pull request by yohei1126**
document for external table resource is missing in the main branch.

## Test Plan

* [x] acceptance tests

* [ ] …

## References

*

### CODE REVIEW

**Comment by yohei1126** [comment]
@ryanking Would you check this? Thanks

**Review by ryanking — APPROVED** [review]

**Comment by yohei1126** [comment]
@ryanking How can I check the failed test?

**Comment by ryanking** [comment]
@yohei1126 when you click on the link (23be3e4) above does it take you to the tests?

**Comment by yohei1126** [comment]
@ryanking I just added the document. I think main branch is broken?

```
=== RUN   TestAccExternalTable
    external_table_acceptance_test.go:14: Step 1/1 error: Error running apply: 2021/01/19 18:29:41 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
        
        Error: error creating externalTable jkdvwnnjek: 002003 (02000): SQL compilation error:
        Database 'JKDVWNNJEK' does not exist or not authorized.
```

**Comment by ryanking** [comment]
> I think main branch is broken?

I don't see any failing tests on the main branch, but not sure what's going on here.

**Comment by yohei1126** [comment]
#426 can fix the issue?

**Comment by alldoami** [comment]
Hi @yohei1126 sorry to keep you waiting! Yes that PR should fix it, but we're still running into an issue with it. If it is not resolved by EOD, we will get rid of that test. Thanks for being patient!

**Comment by yohei1126** [comment]
@alldoami done

**Pull request merged**
