### PR TITLE
[feature] add monitor execution & execute tasks privileges

### PR DESCRIPTION
**Pull request by haley-roberts**

### CODE REVIEW

**Comment by chriskuchin** [comment]
@ryanking any chance of getting some feedback here? We would like to manage these perms using terraform. Thanks

**Comment by ryanking** [comment]
@chriskuchin Based on the title of the PR I was expecting some tests. Do you think some should be included?

**Comment by chriskuchin** [comment]
If you think it's necessary I can work with haley to add some but the actual tests don't seem like they would be very useful or interesting based on the code changes. I think she titled it with test to try and kick off the test suite.

**Comment by chriskuchin** [comment]
I will have her push a couple mockdb tests to ensure the queries come out right

**Comment by haley-roberts** [comment]
@ryanking I added a couple of tests, let me know if there's anything else you would like

**Pull request merged**
