### PR TITLE
schema_grant to support more than just USAGE

### PR DESCRIPTION
**Pull request by pwnage101**
Define correct list of valid schema grant privileges and actually use it.  Also update unit tests to ensure something other than USAGE works correctly.

Addresses #68.

### CODE REVIEW

**Comment by pwnage101** [comment]
```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/travis/gopath/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:

	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
```

**Comment by pwnage101** [comment]
For now, I have worked around the issue locally by using a go proxy:

```
export GOPROXY=https://goproxy.io
make test
```

**Comment by ryanking** [comment]
@pwnage101 I will take a look at those test failures tomorrow and either fix them or work around them

**Comment by pwnage101** [comment]
In a previous successful build, this was in the console log on travis:

```
Setting environment variables from repository settings
$ export CODECOV_TOKEN=[secure]
$ export SNYK_TOKEN=[secure]
$ export SNOWFLAKE_ACCOUNT=[secure]
$ export SNOWFLAKE_USER=[secure]
$ export SNOWFLAKE_PASSWORD=[secure]
$ export SNOWFLAKE_ROLE=[secure]
```

But in my build:

```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
```

You might have to run the job yourself as one of the CODEOWNERS, and travis might not reject the environment variables.

**Comment by ryanking** [comment]
@pwnage101 yeah to run the builds you would have to set up travis-ci with your own credentials

**Pull request merged**
