### PR TITLE
Add data source for SYSTEM$GET_PRIVATELINK_CONFIG() function

### PR DESCRIPTION
**Pull request by robbruce**
## Test Plan

* [x] acceptance tests

* [x] - This executes SELECT SYSTEM$GET_PRIVATELINK_CONFIG(), which applies for accounts with Business Critical plan; although values are returned from Snowflake either way.

Tests ran

```
$ TF_ACC=1 go test -v ./... -run TestAccSystemGetPrivateLinkConfig_aws
?   	github.com/chanzuckerberg/terraform-provider-snowflake	[no test files]
=== RUN   TestAccSystemGetPrivateLinkConfig_aws
=== PAUSE TestAccSystemGetPrivateLinkConfig_aws
=== CONT  TestAccSystemGetPrivateLinkConfig_aws
--- PASS: TestAccSystemGetPrivateLinkConfig_aws (5.92s)
PASS
ok  	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/datasources	6.353s
?   	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/db	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/provider	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake	(cached) [no tests to run]
?   	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/testhelpers	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/validation	(cached) [no tests to run]
?   	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/version	[no test files]
```

The JSON structure from the function `SELECT SYSTEM$GET_PRIVATELINK_CONFIG()` on all the accounts I have ran against are AWS, so have not been able to verify if there are any different behaviours on Azure, e.g. the config value `privatelink-ocsp-url` may actually come back as documented rather than `privatelink_ocsp-url` so have added belt-n-braces around that.

## References

* https://docs.snowflake.com/en/sql-reference/functions/system_get_privatelink_config.html

### CODE REVIEW

**Comment by alldoami** [comment]
@robbruce could you update your branch? After that we can merge! Thank you for creating this!

**Comment by robbruce** [comment]
@alldoami - merged with main

**Review by alldoami — APPROVED** [review]
Thanks!

**Pull request merged**
