### PR TITLE
Better Azure integration - Pipe + Notification Integration

### PR DESCRIPTION
**Pull request by arkadiuss**
We needed better Azure integration, there are two useful changes:
- added 'INTEGRATION' to pipe resource to support also Azure notifications
- notification integration resource

## Test Plan
* [x] acceptance tests
* [x] manual tests

Notification integration was only tested with Azure. It wasn't tested with GCP

## References
Notification Integration - https://docs.snowflake.com/en/sql-reference/sql/create-notification-integration.html
Pipe - https://docs.snowflake.com/en/sql-reference/sql/create-pipe.html
*

### CODE REVIEW

**Comment by alldoami** [comment]
Can you run `make docs`?

**Comment by arkadiuss** [comment]
Sorry I missed that. Docs updated

**Comment by arkadiuss** [comment]
> Integration tests failure for [5e07f99](https://github.com/chanzuckerberg/terraform-provider-snowflake/actions/runs/900172355)

Tests should be fixed after last commit

**Comment by alldoami** [comment]
Oops my bad. Can you resolve conflicts and I'll retetst? I just merged another PR.

**Comment by arkadiuss** [comment]
> Oops my bad. Can you resolve conflicts and I'll retetst? I just merged another PR.

Sure. Resolved

**Review by alldoami — APPROVED** [review]

**Pull request merged**
