### PR TITLE
docs: Add extensive example of setting up a storage integration

### PR DESCRIPTION
**Pull request by bneijt**
If you do not define the role as a variable, you will end up with a cycle between role and integration, so I thought it would be nice to add a full example for other people to see that relation.

## References

https://docs.snowflake.com/en/user-guide/data-load-s3-config-storage-integration.html

### CODE REVIEW

**Comment by alldoami** [comment]
Hello! Please update this file here: https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/examples/resources/snowflake_storage_integration/resource.tf instead of changing it in this md. We use a plugin that gathers various information across files and compiles it into one.

**Comment by bneijt** [comment]
The PR has been open for a few months now.

Is there something I'm missing?

**Comment by alldoami** [comment]
Ah sorry @bneijt could you fix the conflicts and I'll merge after!

**Comment by bneijt** [comment]
Ah, totally forgot about this PR. The changes are still good, but never got to rebase it.

Better luck next time.

**Pull request closed without merging**
