### PR TITLE
[fix] Extra checks for resources in statefile not found (#188)

### PR DESCRIPTION
**Pull request by edwinbdr**
* Adds checks when resources found in the state file are not found in the Snowflake environment. The resources are then removed from the statefile and a warning is produced.

## Test Plan

* [ ] acceptance tests

* [ ] …

## References

*

### CODE REVIEW

**Comment by lgwacker** [comment]
Great!!

**Review by ryanking — CHANGES_REQUESTED** [review]
Thank you for this, it makes sense. Would it be possible to write some tests for this? I know it might seem a bit laborious, but making changes to this project without writing tests has been biting us pretty hard.

**Comment by lgwacker** [comment]
@ryanking if you could give me some guidance on how to build those tests, I would be glad to write them.

**Comment by lgwacker** [comment]
@edwinbdr I opened a PR to your fork with the tests. Can you merge it and add it to this PR?

**Comment by alldoami** [comment]
Hi @edwinbdr can you fix the conflicts and I will take a look at this again?

**Comment by lgwacker** [comment]
Hi, @alldoami I guess this PR can be closed. I created another with these changes and tests and it was merged already.
https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/339

**Pull request closed without merging**
