### PR TITLE
[fix] doc for importing table

### PR DESCRIPTION
**Pull request by yohei1126**
The target table id is missing on the current doc. This will fix the issue.

## Test Plan

* [x] acceptance tests

* [ ] …

## References

*

### CODE REVIEW

**Comment by yohei1126** [comment]
@ryanking @alldoami Would you check this?

**Comment by alldoami** [comment]
Also, fyi @yohei1126, rk doesn't work at CZI anymore, so it'll be me mainly reviewing PRs until Snowflake starts to take more ownership of it.

**Comment by yohei1126** [comment]
OK thanks. updated the branch.

**Review by alldoami — APPROVED** [review]

**Pull request merged**
