### PR TITLE
[doc] fix doc for snowflake_schema

### LINKED ISSUE #434: Documentation for import resource snowflake_schema incorrect
**Describe the bug**

The documentation for importing a schema on the Terraform Provider Registry is incorrect. On this page:
https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/schema

At the bottom it in the code example it says:
```
format is schema name | privilege | true/false for with_grant_option
terraform import snowflake_schema.example 'schemaName|USAGE|true'
```

It should be:
```
format is schema DbName | schemaName
terraform import snowflake_schema.example 'DbName|schemaName'
```

### PR DESCRIPTION
**Pull request by yohei1126**
* This PR fix the example for `snowflake_schema` resource in the document.
* Fix #434

## Test Plan

* [x] acceptance tests

* [ ] …

## References

* https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/schema

### CODE REVIEW

**Comment by yohei1126** [comment]
@alldoami Would you check this?

**Review by alldoami — APPROVED** [review]
Need to fix conflicts with go.sum

**Comment by yohei1126** [comment]
@alldoami done

**Pull request merged**
