### PR TITLE
Add SCIM access token Datasource

### PR DESCRIPTION
**Pull request by ChrisIsidora**
Added Datasource (Generate) SCIM Access Token. See #550 

## Test Plan

* [x] acceptance tests
* [x] unit tests

## References
https://docs.snowflake.com/en/user-guide/scim-azure.html
*

### CODE REVIEW

**Comment by ChrisIsidora** [comment]
@edulop91 This is related to #550

**Comment by ChrisIsidora** [comment]
@alldoami Can you send another ok to test?

**Comment by ChrisIsidora** [comment]
@alldoami Acceptance tests should be passing now with the new error handling

**Comment by ChrisIsidora** [comment]
@alldoami I think the integration test is failing because the scim integration is not there, should I skip the acceptance test or do you another way that the acceptance test could pass?

**Comment by alldoami** [comment]
@ChrisIsidora let's merge your other PR first

**Comment by ChrisIsidora** [comment]
@alldoami I updated the other PR #556 and already added the resource dependency in this PR. But the other PR should pass and be merged first

**Comment by ChrisIsidora** [comment]
@alldoami The Acceptance tests should be OK now.
image

**Review by alldoami — APPROVED** [review]

**Pull request merged**
