### PR TITLE
feat: Allow in-place renaming of Snowflake tables

### PR DESCRIPTION
**Pull request by nafarlee**
Allow changing the name of Snowflake tables without destroying then recreating the table.

## Test Plan
* [ ] acceptance tests
* [ ] unit tests

## References
- Feature Request: #891 
- [Snowflake Documentation for Renaming a Table](https://docs.snowflake.com/en/sql-reference/sql/alter-table.html#syntax)

### CODE REVIEW

**Comment by alldoami** [comment]
Thanks for contributing @nafarlee! could you update your branch and we can get this merged?

**Comment by nafarlee** [comment]
> Thanks for contributing @nafarlee! could you update your branch and we can get this merged?

You are welcome! Should be up to date now.

**Review by alldoami — APPROVED** [review]

**Comment by alldoami** [comment]
So sorry about not catching these changes! Can you merge again and we'll get this merged!

**Comment by nafarlee** [comment]
> So sorry about not catching these changes! Can you merge again and we'll get this merged!

No worries! Just rebased.

**Pull request merged**
