### PR TITLE
fix: Add valid property AWS_SNS_TOPIC_ARN to AWS_SNS notification provider 

### PR DESCRIPTION
**Pull request by sowmyananjundapa**
Notification integration fixes for [#777 ](https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/777)

- Fix AWS_SNS_TOPIC_ARN a valid argument for notification integration provider
- Documentation, example and import

## Test Plan
CGO_ENABLED=1 go test -race -coverprofile=coverage.txt -covermode=atomic  ./...
?       github.com/chanzuckerberg/terraform-provider-snowflake  [no test files]
ok      github.com/chanzuckerberg/terraform-provider-snowflake/pkg/datasources  0.802s  coverage: 4.2% of statements
?       github.com/chanzuckerberg/terraform-provider-snowflake/pkg/db   [no test files]
ok      github.com/chanzuckerberg/terraform-provider-snowflake/pkg/provider     0.602s  coverage: 28.9% of statements
ok      github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources    11.868s coverage: 55.0% of statements
ok      github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake    0.454s  coverage: 59.7% of statements
?       github.com/chanzuckerberg/terraform-provider-snowflake/pkg/testhelpers  [no test files]
ok      github.com/chanzuckerberg/terraform-provider-snowflake/pkg/validation   0.249s  coverage: 93.1% of statements
?       github.com/chanzuckerberg/terraform-provider-snowflake/pkg/version      [no test files]

* [ ] acceptance tests
Error notifications feature is currently in private preview link reference [here](https://docs.snowflake.com/en/LIMITEDACCESS/data-load-snowpipe-notifications.html) and Snowflake staff need to enable it for that particular account before setting error_integration parameter would work.

## References
https://docs.snowflake.com/en/LIMITEDACCESS/data-load-snowpipe-notifications.html#step-6-enabling-error-notifications-in-pipes

### CODE REVIEW

**Comment by sowmyananjundapa** [comment]
@alldoami  could you please review and approve for Github Actions

**Comment by alldoami** [comment]
Hmm I might be missing something but I only see name changes in this PR...

**Comment by sowmyananjundapa** [comment]
HI @alldoami, 

- Yes I raised a PR for name change of the variable provided. I got the below error while creating the notification integration with terraform plan. 
> `SQL compilation error: invalid property 'AWS_SNS_ARN' for 'INTEGRATION'` 
- I debugged a little more and found the issue was with SQL query [here](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/snowflake/notification_integration_test.go#L66)
- This query expects `AWS_SNS_TOPIC_ARN` instead of `AWS_SNS_ARN`

**Review by alldoami — APPROVED** [review]
I still think we need testing for this, so if you have time please write tests for this soon!

**Comment by sowmyananjundapa** [comment]
Could i request release for new version please.

**Pull request merged**
