### PR TITLE
Support adding, removing and changing the type of columns in tables

### PR DESCRIPTION
**Pull request by edwardbrowncross**
The current behaviour is to drop the table and all its data when a column is added, removed, or modified (#446, #421). This PR mostly fixes this. 

Now supported without having to drop and recreate the table:
* Adding columns
* Removing columns
* Changing the data type of a column

Partially supported:
* Renaming columns - the column is dropped and recreated leading to _some_ data loss. There is not currently any better way to correlate columns than their name.

## Test Plan
* [ ✔] acceptance tests (plus made the existing ones more rigorous)
* [✔ ] snowflake unit tests

## References
#446 
#421

[ALTER TABLE documentation](https://docs.snowflake.com/en/sql-reference/sql/alter-table.html)

### CODE REVIEW

**Comment by AdamDewberry** [comment]
Ooo this looks good, excited for a codeowner to review

**Comment by alldoami** [comment]
@edwardbrowncross could you update your branch with `main`?

**Review by alldoami — APPROVED** [review]

**Pull request merged**
