### PR TITLE
feat: Add 'snowflake_role' datasource

### PR DESCRIPTION
**Pull request by gary-beautypie**
Adds functionality to use snowflake_role as a datasource

## Test Plan
* [x] acceptance tests

## References

* #890 Has been closed for some reason?

### CODE REVIEW

**Comment by gary-beautypie** [comment]
Test failures seem unrelated to this PR but will take a look

**Comment by gary-beautypie** [comment]
Test for NotificationIntegration resource was failing as the plan tries to set the DIRECTION to NULL after the first test step, but in Snowflake this seems to default to INBOUND
Screenshot 2022-04-28 at 19 39 02

**Comment by gary-beautypie** [comment]
appears I misunderstood the Azure integration so have updated the GCP part of the test instead

**Review by alldoami — APPROVED** [review]

**Pull request merged**
